### ISSUE TITLE
Centralize EOC section titles

### ISSUE THREAD

**Issue by kswanson33** [openstax/kitchen#203]
All EOC sections have similar titles/wrappers. Currently, each bake direction for an EOC section reproduces its own title. Ideally, all EOC sections can use the same title template, and just substitute in their own data.

Here is an example with Key Equations:
Current way - https://github.com/openstax/kitchen/blob/main/lib/kitchen/directions/bake_chapter_key_equations.rb
New way - https://gist.github.com/kswanson33/6cb9bfe18e96f86479d1a6ab79e0867f

This should be done for:

- [x] Key Equations
- [x] Summary
- [x] Key Concepts
- [x] Move Exercises to EOC
- [ ] Glossary
- [x] Further Research
- [ ] Suggested Reading

**Comment by LostMojo** [comment]
Small difference with Glossary-- it's data UUID key doesn't have a '.' in front of it's klass

**Comment by LostMojo** [comment]
Suggested reading doesn't quite fit the template-- no metadata
