### ISSUE TITLE
Convert all hardcoded inserted words into I18N translations

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/kitchen#32]
To support Spanish translations KD, this work is necessary.

**Comment by Stackblocks** [comment]
From the duplicate card:

# Description 
Find hardcoded words in Kitchen, e.g. ['Figure' here](https://github.com/openstax/kitchen/blob/master/lib/kitchen/directions/bake_figure.rb#L7) and replace them with I18n translations as discussed in this [PR comment](https://github.com/openstax/kitchen/pull/106#discussion_r568275608).

# More Details
**From the Readme**:  Recognizing that our books will be translated into multiple languages, Kitchen has support for internationalization (I18n). There's a spot for translation files in the locales directory, in which there is currently one en.yml translation file for English. Within our directions code you'll see uses of it like here to title an Example:

`<span class="os-title-label">#{I18n.t(:example)} </span>`
