### ISSUE TITLE
Add US History to kitchen 

### ISSUE THREAD

**Issue by KarinaMendez2** [openstax/kitchen#417]

**Comment by MartaSztuka** [comment]
@KarinaMendez2 hi, there are two problems with the book:
1. One table in Appendix C that doesn't break, is that expected?
![Screenshot from 2021-11-19 14-52-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/642b7ab7-1def-4456-bcfe-d9aeed520214)
2. One quote in note doesn't display properly
![Screenshot from 2021-11-19 14-57-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0b728ae5-8e6a-4f16-b522-5ec50396c540)
![Screenshot from 2021-11-19 15-12-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/861f9321-e99f-4d77-aa7d-053af3844981)
#### PASSED
##### Contents
![Screenshot from 2021-11-19 14-44-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/69dd0a3e-ba88-44ea-ad8d-61caa7e66332)
##### Preface
![Screenshot from 2021-11-19 14-45-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cf3da09f-3f2b-4a22-9792-e2c91142ceb2)
##### Chapter outline
![Screenshot from 2021-11-19 14-45-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c2a01fe8-59a3-43da-93d5-44797ea5ec92)
##### Table
![Screenshot from 2021-11-19 14-51-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/31bb925a-415f-4d98-83b3-9b5b76310374)
##### Figure
![Screenshot from 2021-11-19 14-46-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/37591d63-1033-48ce-bb9a-a7ae67b2b00f)
##### Click and explore
![Screenshot from 2021-11-19 14-46-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/09d990bc-efd4-4db6-8386-01dcc2f7d463)
##### My story
![Screenshot from 2021-11-19 14-49-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ddd1b032-fa9a-4dc5-a65a-f24dc8002d3c)
##### Americana
![Screenshot from 2021-11-19 14-48-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fdcab1b0-c374-49d2-8fb9-dfc571df1632)
##### Defining American
![Screenshot from 2021-11-19 14-55-30.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/19229bc2-175e-4b8c-b6f8-5135567dc082)
##### Key terms
![Screenshot from 2021-11-19 14-48-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6f0fa37c-7ea5-4c1e-9104-c9424ae37f81)
##### Summary
![Screenshot from 2021-11-19 14-49-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/62b35cfa-676c-4205-9cb4-cf3fa5e6a27e)
##### Review questions
![Screenshot from 2021-11-19 14-50-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8acc7b64-54e5-49f4-b8d6-2b4a43f2f4f5)
##### Appendices
![Screenshot from 2021-11-19 14-53-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0422bcf3-0a5a-4b33-b8bd-9cd25e1f36b9)
##### Answer key
![Screenshot from 2021-11-19 14-54-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/187704a3-0339-4f84-9144-cb236ea692ac)
##### Index
![Screenshot from 2021-11-19 14-54-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/64d5cfc9-ec6a-4980-96b2-c190e03d1f81)

**Comment by MartaSztuka** [comment]
@KarinaMendez2 I've tested the book again, Appendix C and quote in Defining America still look a little wrong.
![Screenshot from 2021-11-30 11-46-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6ff7ecd1-5170-412d-afda-687bd6431e1c)
![Screenshot from 2021-11-30 11-47-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/24648fe5-7b2b-45f2-ae6b-52cef59e546b)

**Comment by lwtchu** [comment]
@MartaSztuka can you open separate cards for the two issues you found in cnx-recipes?

**Comment by MartaSztuka** [comment]
Here are cards for those two issues, I'm closing this one.
https://app.zenhub.com/workspaces/ce-styles-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/4276
https://app.zenhub.com/workspaces/ce-styles-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/4275

**Comment by lwtchu** [comment]
@MartaSztuka thank you marta <3
