### ISSUE TITLE
statistics - missing spanish translation

### ISSUE THREAD

**Issue by lwtchu** [openstax/kitchen#433]
![Screen Shot 2021-10-28 at 8 40 52 AM](https://user-images.githubusercontent.com/11299125/139285794-f6cf58b5-3ebf-4d5f-8800-0b38d434749e.png)

this is in intro statistics Spanish (statistics recipe) 

osbooks-introduccion-estadistica-bundle/introducción-estadística - for you Alan

**Comment by Stackblocks** [comment]
- [x] Displays OK with current code & content

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/eae72588-367e-474f-abc4-e10e92d7e80b)
