### ISSUE TITLE
Use transliteration in Index only in non Polish books

### ISSUE THREAD

**Issue by wilkus27** [openstax/kitchen#442]
In Polish books first letters of terms shouldn't be transliterated. They should be grouped by letters with accents too.

For example:

![image](https://user-images.githubusercontent.com/40228854/140937521-16095c78-4866-4ebb-9cc4-9b474986355c.png)

these terms should be grouped by Ć.

**Comment by wilkus27** [comment]
### Information for tester

Kitchen fix and updated pl-psychology recipe are merged to main, but not released yet.

**Comment by MartaSztuka** [comment]
#### PASSED
##### webview
https://openstax.org/books/psychologia-polska/pages/skorowidz-rzeczowy
![Screenshot from 2021-11-15 11-22-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/83eaf854-282d-4de6-b28f-e2a528f4478f)
##### PDF
![Screenshot from 2021-11-15 11-23-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/96ae30a5-c1ab-4aa8-bdf2-ce3dcf6e69db)
