### ISSUE TITLE
Write a spec for the `Kitchen::Ancestor` class

### ISSUE THREAD

**Issue by jpslav** [openstax/kitchen#50]
Use RSpec (standard Ruby testing framework) to write a set of tests for the `Kitchen::Ancestor` class. This class wraps an `ElementBase` object (as in an XML element), attaches a `type` to it, and tracks the number of descendants it has of various types (i.e. to track the number of child elements for numbering purposes).

If you look at test coverage, you'll see that [this class is mostly covered already](https://codecov.io/gh/openstax/kitchen/src/master/lib/kitchen/ancestor.rb) -- that's because other higher-level specs test code that makes a lot of use of ancestors. Nevertheless, for such a fundamental class we should have a full spec dedicated to it, which you'll add via this issue.

**Comment by brittany-johnson** [comment]
PR merged, closing issue https://github.com/openstax/kitchen/pull/76
